name: Post Comment in Jira for PR
on: [pull_request]
  
jobs:
  Commit_Checker:
    runs-on: ubuntu-latest
    
    steps: 
        - name: Login
          uses: atlassian/gajira-login@master
          env:
            JIRA_BASE_URL: "https://nanao.atlassian.net"
            JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
            JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
            
        - name: Parse Jira Keys from Commit
          id: jira_keys
          if: always()
          uses: HighwayThree/jira-extract-issue-keys@master
          with:
            is-pull-request: ${{ github.event_name == 'pull_request' }}
            #parse-all-commits: ${{ github.event_name == 'push' }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Push Build Info to Jira
          if: steps.jira_keys.outputs.jira-keys != ''
          id: push_build_info_to_jira
          uses: HighwayThree/jira-upload-build-info@master
          with:
            cloud-id: '${{ secrets.CLOUD_ID }}'
            client-id: '${{ secrets.CLIENT_ID }}'
            client-secret: '${{ secrets.CLIENT_SECRET }}'
            pipeline-id: '${{ github.repository }} ${{ github.workflow }}'
            build-number: ${{ github.run_number }}
            build-display-name: 'Workflow: ${{ github.workflow }} (#${{ github.run_number }})'
            build-state: "${{ env.BUILD_STATE }}"
            build-url: '${{github.event.repository.url}}/actions/runs/${{github.run_id}}'
            update-sequence-number: '${{ github.run_id }}'
            last-updated: '${{github.event.head_commit.timestamp}}'
            issue-keys: "${{ steps.jira_keys.outputs.jira-keys }}"
            commit-id: '${{ github.sha }}'
            repo-url: '${{ github.event.repository.url }}'
            build-ref-url: '${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}'        
        
        - name: Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"       
        - name: Comment on issue
          uses: atlassian/gajira-comment@master
          with:
            issue: RKSA-2
            comment: "${{ github.event.pusher.name }} pushed to repository: ${{ github.event.repository.full_name }}"
