name: Master Workflow - JIRA Update
on: [pull_request]
  
jobs:
      JIRA-Status-Update:
        runs-on: ubuntu-latest
        steps: 
        - name: Login
          uses: atlassian/gajira-login@master
          env:
            JIRA_BASE_URL: "https://nanao.atlassian.net"
            JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
            JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
        
        - name: Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      
        - name: Comment on issue
          uses: atlassian/gajira-comment@master
          with:
            issue: RKSA-2
            comment: ${{ github.event.pusher.name }} Pull Request Opened for - ${{ github.event.repository.full_name }} ${{ github.head_ref }} branch at ${{ steps.date.outputs.date }}  
